--35)

SELECT NumPil
FROM VOLS V JOIN AVIONS A ON V.NumAv = A.NumAv
WHERE A.NomAV = "Airbus A340";

--25) DIFFICILE

SELECT NumCl, NomCl
FROM CLIENTS C JOIN RESERVATIONS R ON C.NumCl = R.NumCl
      AND RESERVATIONS R JOIN VOLS V ON R.NumVol = V.NumVol
WHERE --???;

--14)

SELECT NumVol, NbPlaces
FROM RESERVATIONS
WHERE NumVol = 'V101' || NumVol= 'V222';

--29)

SELECT NumVol, NomAv
FROM VOLS V JOIN AVIONS A ON V.NumAv = A.NumAv
WHERE V.VilleA = 'Marseille';

--12)

SELECT distinct COUNT(VilleA)
FROM VOLS

--10)

SELECT COUNT(NumPil)
FROM PILOTES
WHERE VillePil = 'Nice';

--11)

SELECT (extract(year from CURRENT_DATE)-NaisPil)/COUNT(NumPil)
FROM PILOTES

--16)

SELECT NomCl, Classe
FROM RESERVATIONS R JOIN CLIENTS C ON R.NumCl=C.NumCl
WHERE R.NumVol='V790';

--26) PAS SUR DUTOUT , COUPURE ?

SELECT NumPil
FROM VOLS
WHERE  VilleD != 'Paris';

--22)

SELECT (COUNT(VilleD='Paris')/COUNT(NumVol)
FROM VOLS

--13)

SELECT SUM(NumAV)
FROM AVIONS
WHERE CapAv = null OR CapAv = (MIN(CapAv));
